version: 2.1

jobs:
  build:
    machine: true  
    resource_class: team_2/aws
    steps:
      - run: echo "Hi I'm on a Container Runner!"
      - run: mvn clean install
workflows:
  build-workflow:
    jobs:
      - build



