version: 2.1

jobs:
  say_hello:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run: echo "Say hello to YAML on AWS runner!"

  build_and_test_maven:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout  
      - run: mvn clean install
      
      - run: mvn jacoco:report
      
      - run: mvn surefire-report:report

      
      - store_artifacts:
          path: target/site/jacoco/index.html
          destination: code-coverage

      
      - store_test_results:
          path: target/surefire-reports

       # Docker Build Step
      - setup_remote_docker  # Enable Docker commands in CircleCI
      - run:
          name: Build Docker Image
          command: docker build -t calculator-app:latest .
          


workflows:
  hello_and_goodbye:
    jobs:
      - say_hello
      - build_and_test_maven
